### ISSUE TITLE
args.dataset formation

### ISSUE THREAD

**Issue by abdullah-al-masud** [brian-xu/IGGAN#3]
Hi there,

I intended to play around with the code you provide and wanted to know the data set formation. I have already downloaded the ShapeNet dataset. Kindly please let me know how to set args.dataset parameter inside utils.py

**Comment by brian-xu** [comment]
Hi,

The parameter should lead to a folder that contains a subfolder with the relevant data for training the model.
Example:
```
data (for train_nr.py)/
├─ chair_models (.binvox)/
```

```
data (for main.py)/
├─ chair_images (.png)/
```
